### ISSUE TITLE
Exception in thread "main" java.lang.ClassCastException

### ISSUE THREAD

**Issue by daryl-sf** [triaxtec/openapitools-generator-action#22]
Hi, I've started getting this error when generating docs. I'm not sure how to debug. Any help understanding why this exception is thrown would be helpful.

```
Status: Downloaded newer image for openapitools/openapi-generator-cli:latest
[main] INFO  o.o.codegen.DefaultGenerator - Generating with dryRun=false
[main] INFO  o.o.c.ignore.CodegenIgnoreProcessor - No .openapi-generator-ignore file found.
[main] INFO  o.o.codegen.DefaultGenerator - OpenAPI Generator: ruby (client)
[main] INFO  o.o.codegen.DefaultGenerator - Generator 'ruby' is considered stable.
[main] INFO  o.o.c.languages.AbstractRubyCodegen - Hint: Environment variable 'RUBY_POST_PROCESS_FILE' (optional) not defined. E.g. to format the source code, please try 'export RUBY_POST_PROCESS_FILE="/usr/local/bin/rubocop -a"' (Linux/Mac)
Exception in thread "main" java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
	at org.openapitools.codegen.languages.RubyClientCodegen.processOpts(RubyClientCodegen.java:208)
	at org.openapitools.codegen.DefaultGenerator.configureGeneratorProperties(DefaultGenerator.java:255)
	at org.openapitools.codegen.DefaultGenerator.generate(DefaultGenerator.java:945)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:487)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
Error: Process completed with exit code 1.
```

workflow.yml
```
- name: Generate Client
        # if: steps.get_spec.outputs.next_version != 0
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: ruby
          config-file: api_client_ruby/openapi-generator-config.yaml
          openapi-url: $API_URL
          command-args: -o api_client_ruby
```

**Comment by dbanty** [comment]
Does this happen when you run the generator directly, or only via the action? I wouldn't _expect_ the action to cause a Java exception, but it's possible something is formatted wrong.

**Comment by daryl-sf** [comment]
I found the issue. I updated the slack channel but forgot to update here.

The problem was in my `openapi-generator-config.yaml` when I set a `gemVersion` to an integer. 

``` yaml
gemVersion: 4 # this is an int and would trigger the error
gemVersion: "4" # explicit string and would work
gemVersion: 4.0.0 # this would be treated as a string and work
```

**Comment by dbanty** [comment]
Glad you figured it out!
